import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.io.*;
import java.util.*;

/**
 * Lucas Beasley
 * 09/25/17
 * Generating annotations using NCBO Annotator.
 */

public class Annotation {
    static final String REST_URL = "http://data.bioontology.org";
    static final ObjectMapper mapper = new ObjectMapper();

    public static void main(String[] args) {
        //map containing file names and the annotations generated by NCBO's annotator
        Map<String, JsonNode> GOannos = new HashMap<>();

        //input directory that contains raw text files (.txt)
        File inDirectory = new File("rawtext");

        //output directory
        File outDirectory = new File("output");

        //retrieve annotations from NCBO's annotator and write them to their respective files
        getAnnos(inDirectory, outDirectory);
    }

    private static String getWord(String beginInd, String endInd, String filename){
        String inText = "", text = "";

        filename = filename.substring(filename.indexOf('/')+1, filename.length()-4);
        filename = "rawtext/" + filename + ".txt";
        File filen = new File(filename);
        int begin = Integer.parseInt(beginInd);
        int end = Integer.parseInt(endInd);

        try{
            Scanner scan = new Scanner(filen);
            while(scan.hasNextLine()){
                text += scan.nextLine();
            }
            inText = text.substring(begin, end);
        } catch (FileNotFoundException ex) {
            System.out.println("Error: File not found.");
            System.out.println("File path: " + filename);
        }
        return inText;
    }

    /***
     * getAnnos pulls text data from input text files and gets annotations from NCBO's annotator
     * @param inDirectory - directory of raw text data
     * @param outDirectory - directory for output of tab-separated annotation files
     */
    private static void getAnnos(File inDirectory, File outDirectory){
        String filename, text = "", json, urlParams;

        try{
            //get api key
            Scanner scan = new Scanner(new File("api_key.txt"));
            final String API_KEY = scan.nextLine();
            scan.close();

            try{
                //pull text data from each file and pass to NCBO
                for (File inputFile : inDirectory.listFiles()){
                    //get name of file and remove ".txt"
                    filename = inputFile.getName();
                    filename = filename.substring(0, filename.length()-4);

                    scan = new Scanner(inputFile);
                    JsonNode annotations;

                    //pull text from paper
                    while(scan.hasNextLine()){
                        text += scan.nextLine();
                    }

                    //encode text
                    text = URLEncoder.encode(text, "utf-8");
                    urlParams = "ontologies=GO&text=" + text;

                    //pass text to NCBO
                    annotations = jsonToNode(post(REST_URL + "/annotator", urlParams, API_KEY));

                    //write annotations to file
                    writeOut(filename, annotations, outDirectory);

                    //reset value
                    text = "";
                }
            } catch (FileNotFoundException ex){
                System.out.println("Error: File not found.");
            } catch (UnsupportedEncodingException ex){
                System.out.println("Error: Unsupported encoding.");
            }
        }catch (FileNotFoundException ex){
            System.out.println("Error: File not found. Cannot retrieve API key.");
        }

    }

    /***
     * JsonNode
     * @param jsonfile
     * @return
     */
    private static JsonNode jsonToNode(String jsonfile) {
        JsonNode root = null;

        try {
            root = mapper.readTree(jsonfile);
        } catch (JsonProcessingException e){
            e.printStackTrace();
        } catch (IOException ex){
            ex.printStackTrace();
        }

        return root;
    }

    /***
     * post creates a POST request to NCBO's Annotator
     * @param createdURL - url passed to Annotator
     * @param urlParams - parameters used to create the url
     * @return annotations from text files
     */
    private static String post(String createdURL, String urlParams, String API_KEY){
        URL url;
        HttpURLConnection connection;
        String line, result = "";

        try{
            //setup connection and connect
            url = new URL(createdURL);
            connection = (HttpURLConnection) url.openConnection();
            connection.setDoInput(true);
            connection.setDoOutput(true);
            connection.setInstanceFollowRedirects(false);
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Authorization", "apikey token=" + API_KEY);
            connection.setRequestProperty("Accept", "application/json");
            connection.setRequestProperty("charset", "utf-8");
            connection.setUseCaches(false);

            DataOutputStream outputStream = new DataOutputStream(connection.getOutputStream());
            outputStream.writeBytes(urlParams);
            outputStream.flush();
            outputStream.close();
            connection.disconnect();

            //get output
            BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));

            line = reader.readLine();
            while(line != null){
                result += line;
                line = reader.readLine();
            }
            System.out.println("Made it"); //debugging
            reader.close();
        } catch (MalformedURLException ex){
            System.out.println("Error: Malformed URL.");
        } catch (IOException ex){
            System.out.println("Error: Connection error.");
        }
        return result;
    }

    /***
     * writeOut creates a file and writes the annotations of a text file to the tab-separated file
     * @param filename - name of input/output file
     * @param annotations - annotations from a file
     * @param directory - output file for .tsv files
     */
    private static void writeOut(String filename, JsonNode annotations, File directory){
        String id, to, from, matchType, text, inRawText;
        int fromfix;
        String[] annos;
        ArrayList annosss = new ArrayList();
        JsonNode details;

        //setup output filename
        filename = directory + "/" + filename + ".tsv";
        File filen = new File(filename);


        //create and write to file
        try (PrintWriter writer = new PrintWriter(filen)) {
            for (JsonNode a : annotations){
                //pull the GO:ID
                id =  a.get("annotatedClass").get("@id").asText();
                id = "GO:" + id.substring(id.length()-7);
                writer.println("ID: " + id);
                //pull the list of annotations
                details = a.get("annotations");

                writer.println("StartIndex\tEndIndex\tGO:ID\tTerm\tOntologyTerm\tMatchType");
                for(JsonNode anno : details){
                    //details for each annotation
                    from = anno.get("from").asText();
                    to = anno.get("to").asText();
                    matchType = anno.get("matchType").asText();
                    text = anno.get("text").asText();

                    //***"From" field has an error and is off by one for the index of the the word***
                    //fix "from" index
                    fromfix = Integer.parseInt(from);
                    from = Integer.toString(--fromfix);

                    inRawText = getWord(from, to, filename);

                    writer.println(from + "\t" + to + "\t" + matchType + "\t" + text + "\t" + inRawText);
                }
                writer.flush();
            }
            writer.close();
        } catch (FileNotFoundException ex) {
            System.out.println("Error: File not found; could not write.");
            System.out.println("File path: " + filename);
        }
    }
}